name: JaklUtils
main: de.jakllp.jaklutils.main.JaklUtils
version: ${project.version}
api-version: 1.17
commands:
  JaklUtils:
    description: Help for all Commands
  makeLeash:
    description: Creates a point of a Leash
  toggleLeash:
    description: Toggles Fence-Leashing
  toggleKnot:
    description: Toggles Fence-Knotting
  jaklsilent:
    description: Silences unimportant messages from this plugin
  abortleash:
    description: Abort a leash-setting